
## Pulsewatch Application Properties
spring.application.name=pulsewatch
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

## JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.pulsewatch.telemetry.model

pulsewatch.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}
pulsewatch.kafka.telemetry-topic=${KAFKA_TELEMETRY_TOPIC}

pulsewatch.kafka.ai-consumer.group-id=${KAFKA_AI_CONSUMER_GROUP_ID}
pulsewatch.kafka.anomaly-topic=${KAFKA_ANOMALY_TOPIC}

## Spring AI Configuration
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.model=${OPENAI_CHAT_MODEL}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL}

## Pulsewatch Custom Configuration
pulsewatch.anomaly.errorRateThreshold=${ANOMALY_ERROR_RATE_THRESHOLD}
pulsewatch.anomaly.p95LatencyThresholdMs=${ANOMALY_P95_LATENCY_THRESHOLD_MS}
pulsewatch.anomaly.spikeMultiplier=${ANOMALY_SPIKE_MULTIPLIER}
pulsewatch.monitoring.window.minutes=${MONITORING_WINDOW_MINUTES}
pulsewatch.telemetry.endpoint.url=${TELEMETRY_ENDPOINT_URL}